let questions = [
    {
        "question":"apple？",
        "answers":[
            ["a",1],
            ["b",0],
            ["c",0]
        ]
    },
    {
        "question":"b？",
        "answers":[
            ["1",1],
            ["2",0],
            ["23",0]
        ]
    },
    {
        "question":"c？",
        "answers":[
            ["2",1],
            ["23",0],
            ["72",0]
        ]
    },
    {
        "question":"d？",
        "answers":[
            ["2",1],
            ["8",0],
            ["62",0]
        ]
    },
    {
        "question":"e？",
        "answers":[
            ["2",1],
            ["52",0],
            ["7",0]
        ]
    },
    {
        "question":"f？",
        "answers":[
            ["5",1],
            ["2",0],
            ["6",0]
        ]
    },
    {
        "question":"g？",
        "answers":[
            ["2",1],
            ["8",0],
            ["21",0]
        ]
    },
    {
        "question":"h？",
        "answers":[
            ["55",1],
            ["5",0],
            ["2",0]
        ]
    },
    {
        "question":"ii？",
        "answers":[
            ["4",1],
            ["5",0],
            ["6",0]
        ]
    },
    {
        "question":"j？",
        "answers":[
            ["1",0],
            [".",1],
            ["3",0]
        ]
    }
    
];

